#define __cs_MUTEX_INITIALIZER          PTHREAD_MUTEX_INITIALIZER
#define __cs_COND_INITIALIZER          PTHREAD_COND_INITIALIZER
#define __cs_RWLOCK_INITIALIZER          PTHREAD_RWLOCK_INITIALIZER
#define __cs_BARRIER_SERIAL_THREAD          PTHREAD_BARRIER_SERIAL_THREAD
#define __cs_CANCEL_ASYNCHRONOUS          PTHREAD_CANCEL_ASYNCHRONOUS
#define __cs_CANCEL_ENABLE          PTHREAD_CANCEL_ENABLE
#define __cs_CANCEL_DEFERRED          PTHREAD_CANCEL_DEFERRED
#define __cs_CANCEL_DISABLE          PTHREAD_CANCEL_DISABLE
#define __cs_CANCELED          PTHREAD_CANCELED
#define __cs_CREATE_DETACHED          PTHREAD_CREATE_DETACHED
#define __cs_CREATE_JOINABLE          PTHREAD_CREATE_JOINABLE
#define __cs_EXPLICIT_SCHED          PTHREAD_EXPLICIT_SCHED
#define __cs_INHERIT_SCHED          PTHREAD_INHERIT_SCHED
#define __cs_MUTEX_DEFAULT          PTHREAD_MUTEX_DEFAULT
#define __cs_MUTEX_ERRORCHECK          PTHREAD_MUTEX_ERRORCHECK
#define __cs_MUTEX_NORMAL          PTHREAD_MUTEX_NORMAL
#define __cs_MUTEX_RECURSIVE          PTHREAD_MUTEX_RECURSIVE
#define __cs_MUTEX_ROBUST          PTHREAD_MUTEX_ROBUST
#define __cs_MUTEX_STALLED          PTHREAD_MUTEX_STALLED
#define __cs_ONCE_INIT          PTHREAD_ONCE_INIT
#define __cs_PRIO_INHERIT          PTHREAD_PRIO_INHERIT
#define __cs_PRIO_NONE          PTHREAD_PRIO_NONE
#define __cs_PRIO_PROTECT          PTHREAD_PRIO_PROTECT
#define __cs_PROCESS_SHARED          PTHREAD_PROCESS_SHARED
#define __cs_PROCESS_PRIVATE          PTHREAD_PROCESS_PRIVATE
#define __cs_SCOPE_PROCESS          PTHREAD_SCOPE_PROCESS
#define __cs_SCOPE_SYSTEM          PTHREAD_SCOPE_SYSTEM

#define __cs_attr_t pthread_attr_t
#define __cs_cond_t pthread_cond_t
#define __cs_condattr_t pthread_condattr_t
#define __cs_key_t pthread_key_t
#define __cs_mutex_t pthread_mutex_t
#define __cs_mutexattr_t pthread_mutexattr_t
#define __cs_once_t pthread_once_t
#define __cs_rwlock_t pthread_rwlock_t
#define __cs_rwlockattr_t pthread_rwlockattr_t
#define __cs_t pthread_t
#define __cs_attr_destroy pthread_attr_destroy
#define __cs_attr_getdetachstate pthread_attr_getdetachstate
#define __cs_attr_getguardsize pthread_attr_getguardsize
#define __cs_attr_getinheritsched pthread_attr_getinheritsched
#define __cs_attr_getschedparam pthread_attr_getschedparam
#define __cs_attr_getschedpolicy pthread_attr_getschedpolicy
#define __cs_attr_getscope pthread_attr_getscope
#define __cs_attr_getstackaddr pthread_attr_getstackaddr
#define __cs_attr_getstacksize pthread_attr_getstacksize
#define __cs_attr_init pthread_attr_init
#define __cs_attr_setdetachstate pthread_attr_setdetachstate
#define __cs_attr_setguardsize pthread_attr_setguardsize
#define __cs_attr_setinheritsched pthread_attr_setinheritsched
#define __cs_attr_setschedparam pthread_attr_setschedparam
#define __cs_attr_setschedpolicy pthread_attr_setschedpolicy
#define __cs_attr_setscope pthread_attr_setscope
#define __cs_attr_setstackaddr pthread_attr_setstackaddr
#define __cs_attr_setstacksize pthread_attr_setstacksize
#define __cs_cancel pthread_cancel
#define __cs_cleanup_push pthread_cleanup_push
#define __cs_cleanup_pop pthread_cleanup_pop
#define __cs_cond_broadcast pthread_cond_broadcast
#define __cs_cond_destroy pthread_cond_destroy
#define __cs_cond_init pthread_cond_init
#define __cs_cond_signal pthread_cond_signal
#define __cs_cond_timedwait pthread_cond_timedwait
#define __cs_cond_wait pthread_cond_wait
#define __cs_condattr_destroy pthread_condattr_destroy
#define __cs_condattr_getpshared pthread_condattr_getpshared
#define __cs_condattr_init pthread_condattr_init
#define __cs_condattr_setpshared pthread_condattr_setpshared
#define __cs_create pthread_create
#define __cs_detach pthread_detach
#define __cs_equal pthread_equal
#define __cs_exit pthread_exit
#define __cs_getconcurrency pthread_getconcurrency
#define __cs_getschedparam pthread_getschedparam
#define __cs_getspecific pthread_getspecific
#define __cs_join pthread_join
#define __cs_key_create pthread_key_create
#define __cs_key_delete pthread_key_delete
#define __cs_mutex_destroy pthread_mutex_destroy
#define __cs_mutex_getprioceiling pthread_mutex_getprioceiling
#define __cs_mutex_init pthread_mutex_init
#define __cs_mutex_lock pthread_mutex_lock
#define __cs_mutex_setprioceiling pthread_mutex_setprioceiling
#define __cs_mutex_trylock pthread_mutex_trylock
#define __cs_mutex_unlock pthread_mutex_unlock
#define __cs_mutexattr_destroy pthread_mutexattr_destroy
#define __cs_mutexattr_getprioceiling pthread_mutexattr_getprioceiling
#define __cs_mutexattr_getprotocol pthread_mutexattr_getprotocol
#define __cs_mutexattr_getpshared pthread_mutexattr_getpshared
#define __cs_mutexattr_gettype pthread_mutexattr_gettype
#define __cs_mutexattr_init pthread_mutexattr_init
#define __cs_mutexattr_setprioceiling pthread_mutexattr_setprioceiling
#define __cs_mutexattr_setprotocol pthread_mutexattr_setprotocol
#define __cs_mutexattr_setpshared pthread_mutexattr_setpshared
#define __cs_mutexattr_settype pthread_mutexattr_settype
#define __cs_once pthread_once
#define __cs_rwlock_destroy pthread_rwlock_destroy
#define __cs_rwlock_init pthread_rwlock_init
#define __cs_rwlock_rdlock pthread_rwlock_rdlock
#define __cs_rwlock_tryrdlock pthread_rwlock_tryrdlock
#define __cs_rwlock_trywrlock pthread_rwlock_trywrlock
#define __cs_rwlock_unlock pthread_rwlock_unlock
#define __cs_rwlock_wrlock pthread_rwlock_wrlock
#define __cs_rwlockattr_destroy pthread_rwlockattr_destroy
#define __cs_rwlockattr_getpshared pthread_rwlockattr_getpshared
#define __cs_rwlockattr_init pthread_rwlockattr_init
#define __cs_rwlockattr_setpshared pthread_rwlockattr_setpshared
#define __cs_self pthread_self
#define __cs_setcancelstate pthread_setcancelstate
#define __cs_setcanceltype pthread_setcanceltype
#define __cs_setconcurrency pthread_setconcurrency
#define __cs_setschedparam pthread_setschedparam
#define __cs_setspecific pthread_setspecific
#define __cs_testcancel pthread_testcancel
#define __cs_barrier_t pthread_barrier_t
#define __cs_barrierattr_t pthread_barrierattr_t
#define __cs_barrier_destroy pthread_barrier_destroy
#define __cs_barrier_init pthread_barrier_init
#define __cs_barrier_wait pthread_barrier_wait
#define __cs_barrierattr_destroy pthread_barrierattr_destroy
#define __cs_barrierattr_getpshared pthread_barrierattr_getpshared
#define __cs_barrierattr_init pthread_barrierattr_init
#define __cs_barrierattr_setpshared pthread_barrierattr_setpshared
#define __cs_sigmask pthread_sigmask


#include <pthread.h>

